source 'https://rubygems.org'

gem 'rails', '4.1.1'
gem 'pg'

gem 'sass-rails', '~> 4.0.3'
gem 'bootstrap-sass'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'devise'
gem 'devise_invitable'
gem 'cancancan', '~> 1.8'
gem 'rolify'
gem 'simple_form', '~> 3.1.0.rc1', github: 'plataformatec/simple_form'
gem 'stripe'
gem 'stripe_event'
gem 'figaro'

group :development, :test do
  gem 'guard'
  gem 'guard-livereload'
  gem 'guard-rspec'
  gem 'rspec-rails'
  gem 'cucumber-rails'
  gem 'capybara'
  gem 'factory_girl_rails'
  gem 'database_cleaner'
  gem 'shoulda-matchers'
  gem 'letter_opener'
  gem 'email_spec'
end  
