development:
  adapter: postgresql
  encoding: unicode
  database: membership_site_development
  pool: 5
  username: postgres
  password: apple7696 
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: membership_site_test
  pool: 5
  username: postgres
  password: apple7696 
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: membership_site_production
  pool: 5
  username: 
  password:
